# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tdd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test
      - name: Generate Report
        id: xunit-viewer
        uses: AutoModality/action-xunit-viewer@v1
      - name: The generated again report
        run: echo "The report is ${{ steps.xunit-viewer.outputs.report-file }}"
      - name: Test
        run: |
          [ ${{ steps.xunit-viewer.outputs.report-file }} == "test-reports/index.html" ]
      - name: Attach the report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: ${{ steps.xunit-viewer.outputs.report-dir }}
